### ISSUE TITLE
Plannen discussiesessie productaanvragen in relatie tot zaken

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/klantinteracties#131]
met aandacht voor oplossing terugbelnotities/contactverzoeken.

**Comment by hdksi** [comment]
Presentatie hier: https://vvng.sharepoint.com/:p:/r/sites/APIsvoorZaakgerichtWerken-Klantinteracties/Gedeelde%20documenten/Klantinteracties/Productaanvragen%20en%20verzoeken/20220523%20-%20Discussiesessie%20verzoeken-productaanvragen.pptx?d=w4c13811f83694499949e4658ec0a5fe8&csf=1&web=1&e=ydS0Zp.

**Comment by JohanBoer** [comment]
Issue stond al op done
