### ISSUE TITLE
Als medewerker van de gemeente wil ik een volledig overzicht van de contact momenten

### ISSUE THREAD

**Issue by VerbeekIT** [VNG-Realisatie/klantinteracties#14]
Als medewerker van de gemeente wil ik een volledig overzicht van de contact momenten van de klant met de gemeente Den Haag. Het maakt hierbij niet uit via welk kanaal de klant contact heeft gezocht (gehad) met de gemeente (Post, eMail, Telefoon, TripleForms, MijnDenHaag (ook lezen ?)  Chat, /Social Media …..) zodat ik een goed beeld heb van de contactmomenten van de klant met de gemeente en de klant beter van dienst kan zijn.

**Comment by JohanBoer** [comment]
Op basis van het huidige informatiemodel is het mogelijk een overzicht te maken van alle klantcontacten van een partij (een gekende persoon of een gekende organisatie).   

T.a.v. enkele comments:

> Post is lastig, want als post is geaddresseerd aan "de bewoners van..." dan is dat niet persé een/één KLANT maar een ADRES. Telefoon, chat, social media, e.d. zijn allemaal gerelateerde aan KLANT.

Deze worden niet als klantcontact vastgelegd. Je weet immers niet wie de ontvanger is. 

> In reactie op de wens ook interacties via social media te kunnen vastleggen kijken hoe we attribuut website-URL in de Klanten API te vervangen door een mechanisme om één of meerdere gebruikersnamen van social media vast te leggen. Daarbij rekening te houden met snel veranderende trends het gebruik van specifieke social media.

Gebruikersnamen van klanten  op Social Media zijn vast te leggen middels het  Digitaal adres.
