### ISSUE TITLE
Maak de wijze waarop land properties zijn opgenomen in de OAS consistent

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/klantinteracties#147]
In de OAS komt op 2 plaatsen een verwijzing voor naar de Land/Gebied-tabel van de BRP. De wijze waarop deze verwijzing wordt opgenomen is echter niet gelijk.
In het component 'KlantAdres' wordt alleen de code van het land ('landcode') opgenomen terwijl in 'SubVerblijfBuitenland' zowel de code van het land ('lndLandcode') als de omschrijving ('lndLandnaam') is opgenomen. Is het niet beter om op beide plaatsen dezelfde properties te gebruiken.

In de Haal Centraal BRP Personen Bevragen API is er overigens ook nog voor gekozen om de landcode en de omschrijving op te nemen in het groepselement 'land' (met daarbinnen de properties 'code' en 'omschrijving'). Neem in overweging die vorm over te nemen.

**Comment by hdksi** [comment]
Splitsen in issue voor consistentievraagstuk en suggestie Haal Centraal ontwerppatroon over te nemen.
