### ISSUE TITLE
Als belanghebbende wil ik weten waarvoor we het concept 'contactmoment' gebruiken, en hoe we contactmoment definiëren

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/klantinteracties#15]
zodat we zo goed mogelijk kunnen aansluiten bij gebruikerswensen met betrekking tot het vastleggen van gegevens over interacties met inwoners en ondernemers, en gemeenten en ontwikkelaars duidelijk maken waarvoor het concept wel, en waarvoor niet wordt gebruikt.

O.a. naar aanleiding van VNG-Realisatie/klantinteracties#14 en VNG-Realisatie/klantinteracties#23.

Eerder is 'contactmoment' in concept als volgt gedefinieerd:

> “Een (aaneengesloten) periode waarbinnen een persoonlijke interactie plaatsvindt tussen een KLANT en de gemeente over één of meerdere onderwerpen.”

Dit is een relatief nauwe definitie. 'Persoonlijke interactie' impliceert dat sprake is van een interactie waarbij de partijen direct op elkaar kunnen reageren, en waarbij informatie wordt verstrekt die specifiek is afgestemd op de vraag van de klant. 'Periode' impliceert dat sprake is van een zekere duur van de interactie. Deze definitie sluit goed aan bij de casus van een telefoongesprek tussen een klant en een medewerker van de gemeente, een gesprek via een chatapp of een e-mailconversatie waarin de specifieke vraag van een klant beantwoord wordt.

Een atomaire, niet-persoonlijke gebeurtenis als het indienen van een formulier om een product te bestellen (door de klant) of het versturen van een brief (door de gemeente) aan alle inwoners binnen een bepaalde doelgroep passen niet goed bij deze definitie, terwijl er vanuit het klantcontactcentrum wel behoefte lijkt te bestaan aan een overzicht waarin ook dit soort interacties terug zijn te zien.

Dus; wat is wel en niet een contactmoment? En waarom wel, of waarom niet?

1. een persoonlijk 'real-time' gesprek tussen klant en medewerker via telefoon of chatapp
2. een serie e-mailberichten waarin een vraag van een klant door één of meerdere medewerkers wordt beantwoord
3. een niet-persoonlijke brief verstuurd door de gemeente aan alle inwoners binnen een bepaalde doelgroep
4. een door een klant ingediend formulier
5. een verzoek aan de klant om meer informatie aan te leveren tijdens het proces van levering van producten of diensten
6. een update over het veranderen van een zaakstatus

Als we bijvoorbeeld 3. beschouwen als contactmoment, dan is het waarschijnlijk ook wenselijk aan een contactmoment een document (zijnde de brief) te kunnen koppelen.

**Comment by JohanBoer** [comment]
Issue stond al op done
