### ISSUE TITLE
Hernoem 'openbareruimteNaam' naar 'straat'

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/klantinteracties#164]
In de HC BRP Personen API is in de proxy variant van de API (de variant die de consumers gebruiken) de property 'naamOpenbareRuimte' niet aanwezig, daar wordt 'straat' gebruikt. De waarde van deze property wordt afgeleid van de GBA property 'openbareruimteNaam' of, als deze er niet is, 'straat'. Om die reden is het denk ik goed om deze property te hernoemen naar 'straat'.

**Comment by melsk-r** [comment]
Zie m.b.t. dit issue ook [hier](https://github.com/VNG-Realisatie/klantinteracties/pull/161#discussion_r910657043) de opmerking van @hdksi.

**Comment by hdksi** [comment]
Conclusie: we hernoemen `naamOpenbareRuimte` naar `straat`. MaxLength blijft 80. Straatnaam halen we weg. Geldt zowel voor correspondentieadres als voor verblijfs-/bezoekadres.
