### ISSUE TITLE
Welke adresattributen moeten verplicht zijn?

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/klantinteracties#169]
Straat/huisnummer/woonplaats is voldoende, net als postcode/huisnummer. Alleen huisnummer daarentegen weer niet. Zijn hier richtlijnen voor?

Zie correspondentie/-verblijfsadres in de Klanten API-specs.

**Comment by hdksi** [comment]
Verplichte attributen bij https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/gegevensgroeptype/natuurlijk_persoon.correspondentieadres_natuurlijk_persoon en https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/gegevensgroeptype/natuurlijk_persoon.verblijfadres_natuurlijk_persoon verschillen van elkaar. Even bij Arjan checken waarom dit het geval is, en naar aanleiding van antwoord verplichtingen bepalen.

**Comment by hdksi** [comment]
@ArjanKloosterboer kan jij hierbij uitsluitsel geven?

**Comment by JohanBoer** [comment]
Alle attributen zijn optioneel. Wat er vastgelegd wordt is afhankelijk van wat de klant wil mededelen danwel van wat de gebruiker wil vastleggen. Er is geen verplichting dat dit een volledig valide adres moet zijn.
