### ISSUE TITLE
'verblijfadres' of 'bezoekadres'?

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/klantinteracties#173]
Het doel van de Klanten API is communiceren met inwoners en ondernemers makkelijker maken. Het opgegeven adres dat niet het correspondentieadres is, wil je waarschijnlijk gebruiken om de klant te bezoeken, ongeacht of die daar ook (officieel) verblijft. Om verwarring met het BRP-verblijfsadres te voorkomen zou ik 'verblijfsadres' dus 'bezoekadres' noemen. Te bespreken.

**Comment by hdksi** [comment]
Omdat je zowel een natuurlijk persoon, niet-natuurlijk persoon als een vestiging kunt 'bezoeken', kiezen we voor `bezoekadres` in plaats van `verblijfsadres`.

**Comment by JohanBoer** [comment]
We kennen een bezoekadres en en correspondentieadres in het informatiemodel.
