### ISSUE TITLE
Als medewerker van de gemeente wil ik kunnen aangeven of een klant een mens of een bedrijf is

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/klantinteracties#181]
...zodat ik alleen relevante gegevens hoef in te vullen.

Met aandacht voor #25. Welke concepten kunnen we hiervoor hanteren zonder dat het heel ingewikkeld wordt?

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
In het informatiemodel is nu de partij als object onderkend die van het type "persoon" of van het type "organisatie" kan zijn.
