### ISSUE TITLE
Branch protection instellen

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/klantinteracties#182]
Zie op de homepagina van deze repo een melding over 'Branch protection'. Moeten we daar iets voor instellen? Zie https://github.com/VNG-Realisatie/klantinteracties/settings/branch_protection_rules/new?branch_name=main.

**Comment by melsk-r** [comment]
Dit gaat over de mogelijkheid die er in GitHub repositories bestaat om checks in te bouwen waaraan een Pull Request moet voldoen voordat deze gemerged kan worden. Bijv. dat er eerst een minimaal aantal approvals moet zijn voordat een PR gemerged kan worden. Volgens mij bestaat er op dit moment niet zo'n behoefte. In dat geval kan dit issue gesloten worden. Als dat wel het geval is dan hoor ik graag aan welke checks behoefte is.

**Comment by hdksi** [comment]
@melsk-r eens met ontbreken van behoefte hieraan. Issue gesloten.
