### ISSUE TITLE
unieke identificatie voor contactmomenten en verzoeken

### ISSUE THREAD

**Issue by erikdelepper** [VNG-Realisatie/klantinteracties#187]
In de interne communicatie wordt vaak verwezen naar een specifiek contactmoment of verzoek. Dan is het handig om met een unieke identificatie te kunnen werken. Deze ontbreekt momenteel in het informatiemodel op zowel contactmoment als verzoek.

**Comment by JohanBoer** [comment]
Alle objecttypen in het klantinteractiesmodel worden voorzien van een uniek identificerend kenmerk.
