### ISSUE TITLE
Als zaakbehandelende organisatie wil ik ook voor niet-natuurlijke personen en vestigingen de juiste adresgegevens kunnen vastleggen

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/klantinteracties#194]
...zodat indien nodig op het juiste adres met betrokkenen contact kan worden gezocht.

Voor Niet-natuurlijke personen is het zonder naar het Handelsregister te verwijzen niet mogelijk om adresgegevens gestructureerd vast te leggen:
![afbeelding](https://user-images.githubusercontent.com/37660390/80585887-5c418c00-8a14-11ea-800e-96d44fb0cdfb.png)

Voor Vestigingen zijn de adresattributen overgenomen van Natuurlijke personen:
![afbeelding](https://user-images.githubusercontent.com/37660390/80585967-7b401e00-8a14-11ea-88ba-7334a23889d9.png)

Vergelijk met RGBZ (Niet-natuurlijk persoon):
![afbeelding](https://user-images.githubusercontent.com/37660390/80585507-bc83fe00-8a13-11ea-9dd5-15754823a7ac.png)

en Vestiging:
![afbeelding](https://user-images.githubusercontent.com/37660390/80585472-ae35e200-8a13-11ea-94c5-de52baf6e68a.png)

Vraag is of dit in de praktijk (al) problemen oplevert.

**Comment by JohanBoer** [comment]
In het informatiemodel is voorzien in het vastleggen van gegevens van een organisatie. Een niet-natuurlijk persoon of een vestiging kan als organisatie worden vastgelegd. Voor het domein klantinteracties is de daadwerkelijke juridische vormgeving van een organisatie niet relevant.
