### ISSUE TITLE
Als taakapplicatie-ontwikkelaar wil ik de taal van de eindgebruiker kunnen vastleggen in de geregistreerde zaak

### ISSUE THREAD

**Issue by sergei-maertens** [VNG-Realisatie/klantinteracties#196]
Onze formulierenoplossing laat eindgebruikers toe om te kiezen tussen beschikbare talen (NL/EN op dit moment). Met de ingevulde formuliergegevens is het mogelijk om deze als zaak te registreren voor de verdere afhandeling. Op dit moment is het niet mogelijk om structureel de taal vast te leggen van de klant.

## Pro's

Structureel opnemen van de taal heeft de volgende voordelen:

* Het is duidelijk voor de behandelaar in welke taal die de klant dient aan te spreken
* De zaken kunnen automatisch gerouteerd worden naar een behandelaar die de betreffende taal machtig is (in de toekomst gaan we ook talen zoals Turks en Arabisch ondersteunen!)

Er is precedent: de taal van een enkelvoudiginformatieobject wordt vastgelegd.

## Alternatieve oplossingen

Eventuele workaround: een eigenschap "taal" definiëren in het zaaktype en deze eigenschap vervolgens specifiëren. Echter dit is minder handig omdat andere applicaties niet weten of en in welke eigenschap de taal vastgelegd is.

**Comment by JohanBoer** [comment]
In de 2023-opzet van klantinteracties is de voorkeurstaal van een klant opgenomen in de Partij en in de Bertrokkene bij klantcontact. Hiermee kan de voorkeurstaal voor hergebruik worden vastgelegd, maar ook de (eventueel afwijkende) voorkeurstaal voor eventuele verder afhandeling (interne taak of zaak) n.a.v het klantcontact. 

Hiermee is deze functionaliteit geborgd.
