### ISSUE TITLE
Als ontwikkelaar wil ik weten welke gegevens ik kan verwachten/moet vullen voor een bepaalde productaanvraag

### ISSUE THREAD

**Issue by joeribekker** [VNG-Realisatie/klantinteracties#199]
...zodat er in het landschap van microservices geen componenten stuk gaan door onverwachte gegevens door te sturen.

Deze user story kan je ook lezen als: "Als gemeente wil ik dat mijn keten blijft werken" om het in gemeente perspectief en het belang van deze user story te schetsen, maar dit is mijn insziens zo generiek dat het weer niets zegt.

**Context**

Ik las in [hier](https://vng-realisatie.github.io/klantinteracties/achtergronddocumentatie/artefacten/1924.html) dat het besluit is genomen: *"Er is geen expliciet concept ‘verzoek’ of ‘productaanvraag’"*, en dat dat wordt gemodelleerd als ``Klantcontact``. Als ik dat goed lees zie ik een relatie naar ``Object (nog uit te werken)``:

![image](https://user-images.githubusercontent.com/96970/233675692-c50b968f-0098-4ff4-b1aa-453664edcdeb.png)

Als ik dit interpreteer dan lees ik dat ``Klantcontact`` vooral de "metadata" bevat van het contactmoment. Het gaat vooral over het wie, wat wanneer, zonder dat het "wat" duidelijk gestructureerd is opgeslagen. Hiervoor kan denk ik ``Object (nog uit te werken)`` worden gebruikt. Ik kan niet goed beoordelen of ``Productaanvraag`` nu buiten scope van deze groep is, of dat hier wordt geïmpliceerd dat het concept uberhaupt geen rol heeft, of dat ``Object`` daar voor bedoeld is.

Als er geen gestructureerde ``Productaanvraag`` is, dan weet een eformulier niet wat hij moet opsturen (en een formulierdesigner niet wat hij moet uitvragen) maar net zo belangrijk: een afhandelcomponent heeft geen zekerheid over de gegevens die het krijgt aangeleverd. En dan gaan dingen stuk (bron: Den Haag/Ritense/Maykin).

Vooropgesteld, **de** "Productaanvraag" bestaat niet. Het is een abstract objecttype, zoals ``Subject`` in RSGB. Echter, volgens mij bestaat een Productaanvraag uit 3 "delen" (attributen ter illustratie):

![image](https://user-images.githubusercontent.com/96970/233682305-edfbba34-818c-46d4-b774-030d4c4e9e19.png)

Metadata kan prima ``Klantcontact`` zijn en ``Object`` de *gestandaardiseerde gegevens* in dit plaatje. *Overige gestructureerde gegevens* moet dan nog ergens een plekje krijgen voor formulier gegevens die geen inhoudelijke rol hebben. Het abstracte objecttype moet gespecialiseerd worden in concrete objecttypen zoals bijvoorbeeld ``Parkeervergunning-Productaanvraag``:

![image](https://user-images.githubusercontent.com/96970/233682347-03e7eb75-0945-4621-b8fb-2ce8107da07f.png)

Op deze manier weet een eformulier dat het persé de *gestandaardiseerde gegevens* moet vullen en het afhandelcomponent weet zo zeker dat het die *gestandaardiseerde gegevens* ook echt krijgt (en daar op kan acteren). De noodzaak hiervan lijkt me duidelijk tenzij we tevreden zijn met een ESB die *extraElementen* uitleest en als het element er niet in staat, dan is dat pech hebben.

En laat die *gestandaardiseerde gegevens* nu juist zo mooi werken via de [Objecttypen API](https://objects-and-objecttypes-api.readthedocs.io/en/latest/introduction/information-model.html). Overigens is Productaanvraag nader uitgewerkt in een ander gremium rondom Productaanvraag en de Producttypencatalogus.

Ik knoop hier ook nog even wat relevante user stories aan elkaar, die ook in andere repositories spelen:

* https://github.com/VNG-Realisatie/klantinteracties/issues/11 - Verzoek komt voort uit best wel een concrete vraag in deze repo.
* https://github.com/VNG-Realisatie/producttypecatalogus/issues/16 - **Producttypencatalogus repo** Gestructureerd vastleggen van welke productaanvraag gegevens nodig zijn

**Acceptatiecriteria**
- [ ] Als eformulier moet ik kunnen valideren dat een formulier de essentiele gegevens bevat (*gestandaardiseerde productaanvraag gegevens*)
- [ ] Als afhandelcomponent moet ik er op aan kunnen dat ik bepaalde gegevens bij een verzoek krijg.

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by rutger-h** [comment]
@joeribekker : mijn indruk uit de presentatie is dat het vastleggen van een Klantcontact volgt uit een verzoek/productaanvraag. Dus: indien er een verzoek/productaanvraag is gedaan, legt de verzendende of ontvangende component vast dat er communicatie heeft plaatsgevonden. Je kan dan (ik denk optioneel) verwijzen naar het verzoek/productaanvraag vanuit het klantcontact. 

Het concept (en formaat van) het verzoek/productaanvraag lijkt me buiten scope van het vastleggen van het klantcontact. Overigens lijkt het dan wel weer een goed idee om dat concept - zowel de naam als de inhoud - vast te leggen.

**Comment by hdksi** [comment]
Goed punt, dat ook al even aan de orde kwam tijdens de bijeenkomst de 20e. We begrijpen je vraag. Dilemma bij de door jou voorgestelde oplossing is dat we de relatie tussen `klantcontact` en `object` bedoeld hebben als equivalent van de relatie tussen `zaak` en `object`, waarbij het aan de zaak gerelateerde object een duurzaam karakter en zelfstandig bestaansrecht heeft. Denk aan een boom waarvoor een kapvergunning moet worden verleend, een pand dat verbouwd gaat worden, een uitkering waarvan de hoogte moet worden bijgesteld etc. - met andere woorden een object waarover een zaak (deels) gaat.

Als de gestandaardiseerde (productspecifieke) gegevens bij een productaanvraag worden vastgelegd als `overig object` hebben die het karakter van (niet-duurzame) procesgegevens. Ze horen bij het `klantcontact` en ontstaan én verdwijnen samen met dat klantcontact. Ze hebben daardoor eerder het karakter van een `bijlage`. Om niet (gestandaardiseerde) structuur plat(ter) te slaan in een ongetypeerd (JSON-)informatieobject stellen we voor om de mogelijkheid te introduceren dat een `bijlage` bij een `klantcontact` kan zijn van het type `informatieobject` óf van het type `overig object`.

Mochten we op een gegeven moment toekomen aan iets als een zelfstandige standaard voor productaanvragen, dan kunnen we de aanvullend de mogelijkheid introduceren om als bijlage een object van type `productaanvraag` te relateren.

**Comment by joeribekker** [comment]
Ik heb nog even gesproken met @hdksi en de comment van @rutger-h nogmaals gelezen.

Als ik het goed heb begrepen wordt er dus binnen de scope van de klantinteracties geen invulling gegeven aan het concept productaanvraag, maar sluit het gremium wat aan de klantinteracties werkt ook niet uit er iets als een productaanvraag kan komen (dat dacht ik namelijk eerst te begrijpen uit de Github tekst). Het valt slechts buiten de grenzen van waar dit IM invulling aan geeft.

Indien een productaanvraag concept wenselijk blijkt, dan kan dat eventueel als (gestructureerde) bijlage worden opgenomen bij klantcontact waarmee de dit IM koppelt aan productaanvraag (wat zijn eigen IM kent).

Ik denk dat ik hiermee uit de voeten kan, hoewel Joeri Diederen hier volgens mij mee aan de slag gaat via de Producttypencatalogus, en ik op een ander deel zit :)

Ik ben assigned en het was mijn issue, dus ik sluit hem dan ook maar. Heropen vooral als jullie er nog iets mee gaan doen of als ik het toch niet goed heb.

**Comment by hdksi** [comment]
Dit is inderdaad wat ik met de laatste zin van mijn reactie wilde aangeven:

> Mochten we op een gegeven moment toekomen aan iets als een zelfstandige standaard voor productaanvragen, dan kunnen we de aanvullend de mogelijkheid introduceren om als bijlage een object van type `productaanvraag `te relateren.

Wellicht ten overvloede, maar ik kan me dus vinden in de samenvatting van @joeribekker.
