### ISSUE TITLE
Suggestie: Partij -> Relatie

### ISSUE THREAD

**Issue by rutger-h** [VNG-Realisatie/klantinteracties#200]
Uit de presentatie bleek dat er al veel is gesproken over de naam voor 'partij'. Toch een suggestie. 

Binnen Domain Drive Design DDD is "ubiquitous language" een belangrijk aspect, waaronder het gebruiken van taal die een brug slaat tussen techniek en eindgebruikers. Je wilt voorkomen dat architecten praten over X en gebruikers over Y. 

Ik denk dat 'partij' niet het woord is dat goed aansluit bij het dagelijks werk van medewerkers / eindgebruikers. Het is niet m.i. niet de term die je gaat zien in user interfaces. Daarop doorgeredeneerd - en kijkend naar soortgelijke systemen om ons heen, is 'relatie' daarin de gangbare term. Deze is ook neutraal: een 'relatie' kan een klant zijn maar ook een ketenpartner, en zowel natuurlijk persoon als niet-natuurlijk rechtspersoon.

**Comment by hdksi** [comment]
Voor wat we nu partij noemen hebben verschillende namen de revue gepasseerd. 'Relatie' was onze eerste keus. Echter bleek uit gesprekken met diverse partijen (😉) dat relatie in CRM-systemen een andere betekenis heeft - namelijk de indicator van het feit dat tussen de gemeente en een klant een relatie bestaat. Onze 'relatie' was daarentegen een alternatieve aanduiding voor wat in zo'n systeem de 'klant' heet. Om begripsverwarring te voorkomen hebben we daarop met pijn in het hart gekozen om wat wij eerder 'relatie' noemden te hernoemen naar 'partij'.

**Comment by hdksi** [comment]
Ik sluit dit issue om het overzicht te behouden. @rutger-h uiteraard is een reactie daarna alsnog welkom.
