### ISSUE TITLE
Suggestie: Klanttaken buiten het CRM domein beleggen

### ISSUE THREAD

**Issue by rutger-h** [VNG-Realisatie/klantinteracties#204]
Het patroon van communicatie tussen Ketenpartners en de gemeente lijkt op het patroon van communicatie tussen Klant en gemeente. We zien in die communicatie taken, berichten en in mindere mate ook verzoek/productaanvragen. 

Praktische voorbeelden: 
1. de communicatie met de politie bij de Haagse pandbrigade. Er worden vanuit een Zaak taken belegd bij de politie, die deze kunnen inzien en afhandelen in een Ketenpartnerportaal. 
2. Amsterdam legt taken bij de Ketenpartner notarisse via een Ketenpartnerportaal.  

De communicatie tussen zaakafhandeling moet (denk ik) verlopen zonder dat het ‘CRM domein’ daarbij betrokken is. Immers, de notarissen en politie zijn geen Klant, en de gegevens zijn in bepaalde gevallen ook zeer gevoelig, waardoor deze verwijderd moeten worden nadat de taak is afgerond. 

Nu zit in het Semantisch informatiemodel de Klanttaak. Ik zou voorstellen deze buiten dit domein te beleggen. Er kan dan wel een contactmoment volgen uit het feit dat een klanttaak uitgezet is. 

Daarmee: 
[Klant contact Sequence diagrammen 1.04.pdf](https://github.com/VNG-Realisatie/klantinteracties/files/11486451/Klant.contact.Sequence.diagrammen.1.04.pdf)

- worden (externe)taken, berichten, verzoek/productaanvragenen portalen en zaakwijzigingsverzoeken op een consistente manier via het informatie arm notificeren afgehandeld (https://vng.nl/projecten/notificatie-services) 
- kan deze communicatie plaatsvinden zonder de noodzaak het CRM domein te gebruiken

Zie in de bijlage de sequence diagrammen vanuit Den Haag, waarin dit patroon wordt toegepast, specifiek het voorbeeld van een externe taak op pagina 17, inclusief het vastleggen van een contactmoment als gevolg van die externe/klanttaak.

**Comment by hdksi** [comment]
We werken het concept `klanttaak` niet uit als onderdeel van eerste versie van de standaard voor Klantinteracties. Daarmee plaatsen we de klanttaak buiten dit domein. Dientengevolge hebben we klantaak ook niet zo diepgaand geanalyseerd als concepten als `partij` en `klantcontact`. De vraag of het wenselijk en logisch is dit concept ook te gebruiken om werk uit te besteden aan leveranciers en ketenpartners moet naar aanleiding van zo'n analyse later beantwoord worden.
