### ISSUE TITLE
[VRAAG] over Objecttype::Object

### ISSUE THREAD

**Issue by rutger-h** [VNG-Realisatie/klantinteracties#205]
Objecttype::Object, deze moet nog uitgewerkt worden geeft het Semantisch informatiemodel aan. Het lijkt me dat dit een link naar naar hetgeen het klantcontact over ging (link naar verzoek/document/zaak/object/etc), maar niet de inhoud – lees het object – zelf? Dan dupliceren we data.

Voorbeeld: in Den Haag wordt het verzoek/productaanvraag door OpenFormulieren als Zaakinformatieobject (PDF) opgeslagen in de Documenten API, waarna deze wordt opgehangen aan de daarna aangemaakte Zaak. Tevens kan hetzelfde verzoek/productaanvraag nogmaals als Zaakobject (JSON) aan de zaak worden gehangen en worden bewaard. 

Als er een Klantcontact zou plaatsvinden over dit verzoek/productaanvraag, dan zou het logisch zijn een verwijzing vast te leggen - niet de inhoud?

**Comment by hdksi** [comment]
In de volgende update van het informatiemodel wordt een duidelijker onderscheid gemaakt tussen de informatie die 'tijdens' het klantcontact wordt uitgewisseld (de inhoud van een gesprek, de inhoud van een formulier) en hetgeen waarover het klantcontact gaat (bijvoorbeeld een zaak of product).

Onze gedachte bij het vastleggen van een aanvraag voor een product of dienst ziet er globaal als volgt uit:
1. de aanvrager vult (online) een formulier in.
3. aan het productaanvraagobject wordt een klantcontact gerelateerd.
4. het formulier wordt ingediend. Er wordt een klantcontact geregistreerd. De inhoud van het formulier wordt geregistreerd als (als productaanvraag getypeerd - maar dit is geen onderdeel van de standaard) object. Dit object wordt als 'inhoudsdeel' aan het klantcontact gerelateerd.
5. op basis van de inhoud van het klantcontact, het productaanvraagobject en eventueel partijgegevens kan nu (geautomatiseerd) een zaak worden aangemaakt.
