### ISSUE TITLE
Suggestie: laten vallen relatie Interne Taak -> Zaak

### ISSUE THREAD

**Issue by rutger-h** [VNG-Realisatie/klantinteracties#206]
Het Objecttype ‘Interne taak’ is (denk ik, als ik de toelichting in de sessie goed heb begrepen) begrijpelijk bedoeld als ‘kattenbelletje’. Een methode om een collega iets te vragen om bij te dragen. 

Ik zie daar een risico op het oprekken van dit fenomeen tot mini-zaak, met interne taakstatussen, archieftermijnen, behandelaars, behandeltermijnen etc. Jan Verbeek heeft dit toegelicht in de sessie. 

Nu is er in het Semantisch informatiemodel een link gelegd tussen Interne Taak en Zaak, de Interne Taak kan leiden tot een Zaak. Dit gaf mensen in de zaal al het idee dat je altijd eerst een Interne Taak aanmaakt, waarna je gaat bepalen of het een Zaak wordt. Ik zie daar een nieuwe ‘verzoek’ discussie opdoemen, onder een nieuwe naam 😊. 

Suggestie: verwijder deze link uit het model.

**Comment by hdksi** [comment]
Eens. Dat een zaak zowel uit een klantcontact als een interne taak kan ontstaan is verwarrend. De 'leidt tot' relatie tussen `interne taak` en `zaak` is een volgende versie van het informatiemodel komen te vervallen.

**Comment by rutger-h** [comment]
Fijn!

**Comment by hdksi** [comment]
^ zie toelichting in #216 voor illustratie bij wijze van registratie van relaties tussen `klantcontact`, `interne taak` en `zaak`.
