### ISSUE TITLE
Contactmomenten hebben PER kanaal een ander datamodel

### ISSUE THREAD

**Issue by HvHees** [VNG-Realisatie/klantinteracties#210]
**Voorstel vanuit Tilburg**
Contactmomenten hebben pér kanaal een ander datamodel zodat álle info (inhoudelijk en metadata)  die vanuit het kanaal meegenomen kan worden, ook wordt meegenomen. 
Daarbij is de (techniek) van de applicatie die het kanaal afhandelt dus bepalend leidend. BV Bij Mail kan je afzender, datum tijd, cc, bcc, meenemen. Bij SMS het telefoonnummer, datum, tijd

**Comment by hdksi** [comment]
Het klantcontact omvat die gegevens die inwoners en ondernemers in een overzicht op bijvoorbeeld een gemeentelijk mijnportaal zouden willen inzien. Vanuit dit perspectief is de techniek die interacties een bepaald kanaal ondersteunt juist níet van belang. Kenmerken die horen bij interacties via een specifiek kanaal zijn dan ook in het informatiemodel niet gemodelleerd. Dat betekent overigens niet dat deze kenmerken als onderdeel van de inhoud van een klantcontact niet gestructureerd vastgelegd zouden mogen worden - het uitwerken hiervan valt echter niet binnen scope van de standaard die we ontwikkelen.
