### ISSUE TITLE
Contactmomenten hebben een relatie “klant” EN een relatie “Afzender/Initiator”

### ISSUE THREAD

**Issue by HvHees** [VNG-Realisatie/klantinteracties#212]
**Voorstel Tilburg**
Contactmomenten (“Relaties” genaamd in SF) hebben een relatie “klant” én een relatie “Afzender/Initiator”. Vaak zijn die twee gelijk aan elkaar maar die Afzender/Initiator wordt gebruikt als er een derde persoon/instantie het initiatief tot benaderen van de gemeente heeft genomen zoals een contactpersoon bij een bedrijf, een bewindvoerder die belt met de gemeente over iemand met schulden etc. etc.  
 
Bij klanten is dus onderscheid mogelijk tussen: 

- Persoonlijk  
- Zakelijk  
- Rol t.o.v. klant en/of proces   (Belanghebbende, Ondersteuning als zorgverlener, etc. etc.)

**Comment by hdksi** [comment]
We hebben gekozen voor een andere modellering. Een `klantcontact` heeft één of meerdere `betrokkenen`. Bij vertegenwoordiging registreren we zowel de `klant` (belanghebbende) als diens vertegenwoordiger(s).
