### ISSUE TITLE
Bij contact met bedrijven, ook de medewerker vastleggen EN hun rol in het bedrijf

### ISSUE THREAD

**Issue by HvHees** [VNG-Realisatie/klantinteracties#213]
**Voorstel Tilburg**
Bij contact met bedrijven, wordt de medewerker vastgelegd EN OOK hun rol in het bedrijf.  
Extra: Het kan ook dat eenzelfde persoon voor of namens meerdere bedrijven werkt (zzp-er, inhuurkracht etc.).

**Comment by hdksi** [comment]
Deze relaties kunnen we in het informatiemodel kwijt. In een bijgewerkte versie hebben we de modellering uitgebreid zodat daarin alle vertegenwoordigingsrelaties die wíj konden bedenken passen. Te beantwoorden vraag is of we die complexiteit in het model - en daarmee de standaard - willen introduceren. We bespreken dit op 6 juli.
