### ISSUE TITLE
Hoe verkrijg je voldoende zekerheid bij registreren van Contactmomenten (zonder DigiD, e-Herkenning) ?

### ISSUE THREAD

**Issue by HvHees** [VNG-Realisatie/klantinteracties#215]
Vraag Tilburg: 
Hoe borg je een grote mate van zekerheid m.b.t. contactmomenten in de mijn-omgeving als je de klant niet met zekerheid (DigiD of E-Herkenning) geïdentificeerd hebt ? 
 
In Tilburg worden aanvullende vragen gesteld (aan de telefoon en/of mail terug en/of bericht terug met vragen als: Wat is uw postcode huisnummer of wat is uw geboortedatum. 
Dit vergt tijd en geeft alsnog geen 100% zekerheid. 
 
Daarentegen is voor ieder klantcontact, om DigiD vragen ook niet klantvriendelijk en daar is DigiD ook niet voor bedoeld. 
 
Toch is er een aanzienlijk risico (zie de aandacht voor “Betrouwbare overheid”) dat de klant in zijn Mijn-omgeving bij het opvragen van contactmomenten: 

- Bepaalde contactmomenten niet terug ziet 
- Contactmomenten terug ziet die hij/zij niet herkent (verkeerde persoon – tweeling ? of iemand met dezelfde naam etc.) 
- Contactmomenten privé wel ziet maar Zakelijk niet (of andersom) 
 
Met name foutieve contactmomenten is een risico vanuit “Betrouwbare overheid”. Maar als identificatie plaatsvindt op basis van telefoonnr, e-mailadressen dan bestaat dit risico terdege. 
 

PS. Bij productaanvragen is dit iets minder aangezien voor het overgrote deel van productaanvragen identificatie (DigiD, e-Herkenning en evt. ophalen bij de balie) verplicht is.

**Comment by hdksi** [comment]
Dit is een heel terechte vraag, waarop de standaard voor klantinteracties helaas geen eenduidig antwoord kan bieden.

We zien hier een botsing tussen dienstverlening en gegevensbescherming. Lastig is dat de wetgever beide heel belangrijk vindt, maar geen concrete handreikingen doet in welke gevallen welk van de twee prevaleert. Om zowel een vanuit gegevensbescherming zeer strenge als meer dienstverleningsgerichte implementatie mogelijk te maken, is het enerzijds mogelijk om contactgegevens van inwoners meermaals vast te leggen (een set na inloggen met DigiD verkregen set contactgegevens die na opnieuw inloggen met DigiD kunnen worden verstrekt, een set na telefonisch contact verkregen contactgegevens, ...). Anderzijds maken we het mogelijk om contactgegevens op te vragen op basis van (combinaties) van andere gegevens dan alleen het BSN/OIN/KVK-nummer.
