### ISSUE TITLE
Voorstellen Klantinteracties: Registreren partij en gevolgen voor Omnichannel doel: Tonen integraal klantbeeld

### ISSUE THREAD

**Issue by HvHees** [VNG-Realisatie/klantinteracties#217]
Zie Toelichting deel 2 – sheet 11 en 12: We hebben uitgebreid gekeken naar de voorbeelden van Henk de Bruin en we snappen dat er bij de registratie van de aanvraag paspoort, omgevingsvergunning en huur sporthal meerdere partijnummers zijn gebruikt.

Gezien vanuit onze Omnichannel-doelstellingen (en voorheen Architectuurthema Omnichannel) vragen we ons wel af hoe dit uitwerkt voor onze KCC-medewerker die we willen voorzien van een integraal klantbeeld zodat hij/zij mee kan denken met de klant (proactieve dienstverlening) en een vergelijkbare informatiepositie heeft.
Ofwel hoe kunnen we een integraal klantbeeld technisch genereren zodat al die contactmomenten en productaanvragen zichtbaar zijn voor de KCC-medewerker (en voor de klant in zijn Mijn-gemeente-omgeving) ?
Of hoe moet een KCC-medewerker gaan werken naar het achterhalen van de juiste aanvraag ? Dit met inachtneming van o.a. privacy-wetgeving.
Dit zouden we geïllustreerd willen zien met meerdere voorbeelden/use cases.

**Comment by hdksi** [comment]
Ik zie deze vraag als variant van #215. Zoals daar gesteld ondersteunt de standaard het door gemeenten maken van verschillende afwegingen tussen gegevensbescherming en verbetering dienstverlening, maar beschrijft die (dus) niet welke afweging gemaakt moet worden. Dat is meer een vraag voor juristen en beleidsmakers dan voor standaardontwikkelaars.
