### ISSUE TITLE
Voorstellen Klantinteracties: Registreren partij en gevolgen voor Omnichannel doel: Klantherkenning.

### ISSUE THREAD

**Issue by HvHees** [VNG-Realisatie/klantinteracties#218]
Toelichting deel 2 – sheet 11 en 12:
Evenzo hebben we tot doel om de klant persoonlijk te ontvangen (met name aan de telefoon) en willen we zijn gegevens op halen op basis van contactgegevens als telefoonnummer, e-mailadres etc.
We zien veel complicaties als:
-      Privénummer dat ook zakelijk wordt gebruikt en andersom
-	Gezinsmail-adres dat wordt opgegeven
-	Vast toestel dat door vader, moeder en meerderjarige kinderen wordt gebruikt
-	ZZP-ers

T.a.v. Issue/Enhancements #217 en #218 denken we NIET dat het datamodel hiervoor aangepast moet worden. Maar zouden we graag uitgewerkt zien hoe technische voorzieningen en/of de interne organisatie hier mee moet omgaan en alsnog de Omnichanneldoelstellingen kan halen waarbij voorbeelden vaak erg goed werken

**Comment by hdksi** [comment]
Anders dan dat je in de `omschrijving` bij `digitaal adres` zou kunnen toevoegen dat bijvoorbeeld sprake is van een mailadres dat door een heel gezin gebruikt wordt zie ik niet goed hoe we deze complicaties als onderdeel van de standaard die we ontwikkelen kunnen wegnemen of verminderen. Misschien helpt het hier om de gewenste functionaliteit helder(der) te krijgen door de vraag in de vorm van een user story('s) te stellen?
