### ISSUE TITLE
Voorstellen Klantinteracties: Toelichting deel 2 – sheet 5: Digitaal adres

### ISSUE THREAD

**Issue by HvHees** [VNG-Realisatie/klantinteracties#219]
Dit nieuwe data-element staat verder niet toegelicht maar we nemen aan dat dit een tabel is met contactadressen van een partij, en dat die gebruikt worden als die partij betrokkene is bij een klantcontact.
En voor een ander Omnichannel-doel: Opgave van het voorkeurskanaal van de klant.

Maar er zou er ook een tweede doel gekoppeld moeten worden aan deze registratie, namelijk klantherkenning, één van de Omnichannel-doelen. Klopt dat ?

Graag dit Data-element t.a.v. functie/doel nog helder toelichten.

**Comment by hdksi** [comment]
`Digitaal adres` is bedoeld om niet-fysieke 'adressen' te registreren waarop de klant bereikbaar is. De gemeente kan door het vullen van een referentielijst voor `soort digitaal adres` zelf bepalen voor welke kanalen (telefoon vast/mobiel, e-mail, whatsapp, twitter, ...) een adres kan worden opgegeven. Het vastleggen van het voorkeurskanaal gebeurt door bij `partij` een (eveneens op basis van in een referentielijst door de gemeente beschreven ondersteunde kanalen) `voorkeurskanaal` te registreren.

Dan het gebruik van digitale adressen voor klantherkenning. Zoals je in #218 kan je op basis van een digitaal adres niet niet met zekerheid vaststellen met wie je te maken hebt. De vraag is hoe erg dat is. Het antwoord op die vraag is afhankelijk van waar we (gemeenten collectief) of je (gemeenten individueel) dienstverlening laat prevaleren boven streng omgaan met persoonsgegevens of vice versa. Zie ook #215. Concreet zien we voor het beantwoorden van deze vraag twee opties. De ene is in de standaard veel mogelijkheden voor bevragen te bieden, waarbij onder andere `digitaal adres` gebruikt kan worden om partijen te filteren. Risico hierbij is dat de standaard mogelijkheden gaat bieden die echt niet mogen of wenselijk zijn. De andere opties is eerst met een werkgroepje van gemeentelijke juristen en dienstverleningsexperts uitzoeken wat mag en gewenst is, en de bevragingsmogelijkheden bij de uitkomsten daarvan aansluiten.
