### ISSUE TITLE
Voorstellen Klantinteracties: Partij - gegevensset

### ISSUE THREAD

**Issue by HvHees** [VNG-Realisatie/klantinteracties#220]
Zie:
- Toelichting Deel 1 – sheet 4 en 5  en Toelichting Deel 2 – diverse sheets 
- swagger-info op Github
([vng-realisatie.github.io/klantinteracties/api_familie_x/variant1/swagger-ui#/Partij/registreerpartij](https://vng-realisatie.github.io/klantinteracties/api_familie_x/variant1/swagger-ui#/Partij/registreerpartij)).

"Partij" kan een persoon of een bedrijf zijn maar bij registratie van de partij wordt niet aangegeven welke van de twee het dan is (is geweest).

In de velddefinities zien we een aantal opmerkelijke zaken:
- Wat is het verschil tussen “ID” en “Nummer” ?
- Waarom wordt UUID niet gebruikt (zie ZGW-API’s) ?
- Waarom is een interne notitie verplicht ?
- Wat is het doel van “Externe identificatie” waar ook o.a. Landcode bij staat en ook nu: Waarom UUID niet gebruikt ?
-

**Comment by hdksi** [comment]
> "Partij" kan een persoon of een bedrijf zijn maar bij registratie van de partij wordt niet aangegeven welke van de twee het dan is (is geweest).

In de vorige voorbeeldversies kon je het onderscheid tussen een `persoon` of `organisatie` inderdaad alleen maken door ofwel een `organisatienaam` ofwel een `persoonsnaam` te registeren. We hebben de voorbeeldspecificaties ondertussen aangepast. In [de nieuwe varianten](https://vng-realisatie.github.io/klantinteracties/api_familie_klantinteracties/klantinteracties/swagger-ui.html#/) wordt expliciet onderscheid gemaakt tussen het registreren van `personen` (/_registreer_persoon) en `organisaties` (/_registreer_organisatie).

> Wat is het verschil tussen “ID” en “Nummer” ?

De definities in het informatiemodel gaven inderdaad onvoldoende uitsluitsel over het verschil tussen deze twee identificerende kenmerken. Het `ID` is een (liefst globaal _vrijwel zeker_ uniek) 'technisch' ID dat 'onder water' wordt gebruikt om gegevenssets aan elkaar te relateren. Het `nummer` is een (tenminste ieder geval binnen de verstrekkende organisatie uniek) 'mensvriendelijk' ID dat bijvoorbeeld aan de telefoon kan worden doorgegeven aan een medewerker om relevante gegevens te kunnen ophalen.

> Waarom wordt UUID niet gebruikt (zie ZGW-API’s) ?

Het informatiemodel of de specificaties stellen niet dan _geen_ uuid moet worden gebruikt, maar vullen ook niet nader in aan welke vormvereisten een `identificatiecode` moet voldoen. Het ligt wel voor de hand dit dichter bij een productiewaardige versie van de specificaties wél te vereisen.

> Wat is het doel van “Externe identificatie” waar ook o.a. Landcode bij staat en ook nu: Waarom UUID niet gebruikt?

Het doel hiervan is het kunnen verwijzen naar in een extern register opgeslagen 'basis'persoons en organisatiegegevens. Een `Extern ID` kan dus een BSN (bron: BRP) of KVK-nummer (bron: handelsregister), maar ook bijvoorbeeld een na inloggen met EIDAS verkregen Deens CPR-nummer (bron niet paraat ;). Iedere registratie van een `externe registratie` krijgt ook een eigen technisch ID-nummer de conventies van een UUID zou kunnen volgen (zie ook hierboven).
