### ISSUE TITLE
Als gebruiker van de Klanten API wil ik weten welke gegevens die in het RSGB aan Natuurlijk Persoon, Niet-Natuurlijk Persoon en Vestiging hangen opvraagbaar zijn bij basisregistraties

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/klantinteracties#24]
...zodat ik de gegevens die _niet_ bij de basisregistraties opvraagbaar zijn en _wel_ nodig zijn bij de behandeling van zaken kan opnemen bij klant.

...met aandacht voor https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/objecttype/natuurlijk_persoon, https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/objecttype/niet-natuurlijk_persoon en https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/objecttype/vestiging

**Comment by HenriKorver** [comment]
Zie PR https://github.com/VNG-Realisatie/klantinteracties/pull/161 voor de aanpassingen aan de OAS, of zie [Redoc](http://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/HenriKorver/klantinteracties/main/specificatie/klanten/openapi.yaml#tag/klanten/operation/klant_create).

**Comment by HenriKorver** [comment]
> 1. Rekeningnummer toevoegen bij 'klant'.

Gedaan.

> 2. Postadres en correspondentieadres samen nemen en mogelijkheid creëren om correspondentieadres in iedere vorm (binnen-/buitenland postbus of 'gewoon' adres vast te leggen bij 'klant'. Onderzoek de mogelijkheden van polymorfie om dit te ondersteunen. Deze correspondentieadresgegevens worden niet altijd in basisregistraties vastgelegd en kan je dus ook vastleggen bij klanten waarvoor een relatie met een basisregistratiesubject is gelegd.

Ik heb onderscheid gemaakt tussen drie vormen van `correspondentieadres`:
- Binnenlandsadres
- Postbusadres
- Buitenlandsadres

Deze heb ik door middel van polymorfie gemodelleerd.

![afbeelding](https://user-images.githubusercontent.com/37145898/176165619-87f081ae-d4ee-4fa2-b53d-d7d76e8daa70.png)

> 3. Verblijfs/bezoek/locatie-adres zijn vastgelegd in de respectievelijke basisregistraties, maar voor klanten zonder verwijzing naar een basisregistratie moeten deze wel bij 'klant' kunnen worden vastgelegd. Vraag is daarbij of je onderscheid moet kunnen maken tussen een verblijfs/bezoek/locatie-adres of dat we deze kunnen platslaan naar zoiets als een algemeen 'bezoekadres' in de Klanten API. Deze bezoekadresgegevens zou je **niet** moeten vastleggen bij klanten waarvoor een relatie met een basisregistratiesubject is gelegd.

Verblijfs/bezoek/locatie-adres heb ik platgeslagen (samengevoegd) in het algemene attribuut `locatieadres`.  Ook hier maak ik gebruik van polymorfie om onderscheid te maken tussen binnenlands- en buitenlandsadres.

![afbeelding](https://user-images.githubusercontent.com/37145898/176166413-97dd315a-f94d-44f2-9cdf-c009befecafa.png)

**Comment by HenriKorver** [comment]
De aangehaakte gegevens die ik hierboven toegevoegd heb aan de Klanten API zijn gebaseerd op het [RGBZ 2.0](https://www.gemmaonline.nl/index.php/RGBZ_2.0_in_ontwikkeling). In het bijzonder de volgende drie objecttype proxies:
- [Natuurlijk persoon](https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/objecttype/natuurlijk_persoon)
- [Niet-natuurlijk persoon](https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/objecttype/niet-natuurlijk_persoon)
- [Vestiging](https://www.gemmaonline.nl/index.php/Rgbz_2.0/doc/objecttype/vestiging)

**Comment by HenriKorver** [comment]
@melsk-r Bovenstaande links naar de objecttypes in het RGBZ zijn gebroken. Weet jij wat eraan de hand is?

**Comment by melsk-r** [comment]
Nee, ik graag Toine vragen of hij er even naar kan kijken.
