### ISSUE TITLE
Als gemeente wil ik dat het mogelijk wordt in één verzoek meerdere (vanuit de klantvraag bij elkaar horende) producten en diensten aan te vragen

### ISSUE THREAD

**Issue by EdwinCoster** [VNG-Realisatie/klantinteracties#36]
...zodat de externe dienstverlening wordt opgezet vanuit het gezichtspunt van de klant en de klant niet meerdere aparte e-formulieren of sessies nodig heeft om één gebeurtenis te registreren

...met aandacht voor het feit dat de ingevoerde gegevens en bijlagen in meer dan één zaak nodig kunnen zijn.

In de huidige RC voor de Klantinteractie API's is dit nog niet gerealiseerd.

Maar dit is wel in lijn met het [Zaakgericht werken in het gegevenslandschap](https://www.gemmaonline.nl/images/gemmaonline/f/f6/20190620_-_Zaakgericht_werken_in_het_Gemeentelijk_Gegevenslandschap_v101.pdf) (paragraaf 4.1) en [de achtergrondinformatie bij verzoeken](https://vng-realisatie.github.io/gemma-zaken/themas/achtergronddocumentatie/verzoeken).

**Comment by JohanBoer** [comment]
Het verzoek is geen concreet object meer in de klantinteracties. De huidige opzet voorziet in de mogelijkheid dat er in 1 klantcontact meerdere vragen, productaanvragen of meldingen gedaan worden.
