### ISSUE TITLE
Als gebruiker van de Productaanvragen API wil ik dat de klant afwijkende contactgevens kan opgeven voor afhandeling daarvan

### ISSUE THREAD

**Issue by hdksi** [VNG-Realisatie/klantinteracties#38]
conform mogelijkheden van 'rol' bij zaak

...met aandacht voor [vul aan]

**Comment by JohanBoer** [comment]
Alhoewel er geen sprake meer is van een productaanvragen API is in de functionaliteit die hier beschreven is voorzien. Het is mogelijk om bij een klantcontact (die een productaanvraag kan bevatten) afwijkende contactgegevens op te nemen die alleen voor het betreffende klantcontact en de afhandeling van eventuele vervolgacties n.a.v. dit klantcontact gelden.
