### ISSUE TITLE
Als gemeente verwacht ik een ID en Referentie op een verzoek ipv identificatie

### ISSUE THREAD

**Issue by erikdelepper** [VNG-Realisatie/klantinteracties#8]
...zodat we ons conformeren aan internationale standaarden (schema.org) 
Vanuit technische overwegingen verwacht ik dat alle resources zijn voorzien van een UUID die als ID onderdeel is van het JSON dataobject. Los daarvan verwacht ik een omschrijving van het verzoek waarover ik met de klant van communiceren. In lijn met schema.org verwacht ik dat we voor menselijk leesbare unieke identificatiecode property “referentie” gebruiken. Met het toevoegen van deze twee properties kan de property “identificatie” komen te vervallen.

**Comment by JohanBoer** [comment]
In het huidige informatiemodel is een attribuut "ID" opgenomen in objecttypen van klantinteracties. Dit is de uniek identificerende code die bijvoorbeeld gevuld kan worden met een UUID. Voor de objecttypen waarover mogelijk met de buitenwerled gecommuniceerd kan worden is een attribuut "Nummer" opgenomen. Dit nummer heeft de rol van referentienummer waarnaar kan worden verwezen door een medewerker, een klant of een vertegenwoordiger.
